services:
  metasploit:
    restart: always
    image: sadparad1se/metasploit-framework:rpc
    container_name: metasploit
    network_mode: host
    environment:
      METASPLOIT_DB_HOST: 127.0.0.1
      METASPLOIT_DB_PORT: 5432
      METASPLOIT_DB_NAME: msf
      METASPLOIT_DB_USERNAME: msf
      METASPLOIT_DB_PASSWORD: msf
    tty: true
    depends_on:
      metasploit_db:
        condition: service_healthy

  metasploit_db:
    restart: always
    image: postgres:16
    container_name: metasploit-db
    environment:
      POSTGRES_PASSWORD: msf
      POSTGRES_USER: msf
      POSTGRES_DB: msf
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - msf_db_data:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready -U $$POSTGRES_USER
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  msf_db_data:
