# https://github.com/rapid7/metasploit-framework/tree/master/lib/msf/core/rpc/v10
# https://docs.metasploit.com/api/Msf/RPC.html

# Auth
AUTH_LOGIN = "auth.login"
AUTH_LOGOUT = "auth.logout"
AUTH_TOKEN_LIST = "auth.token_list"
AUTH_TOKEN_ADD = "auth.token_add"
AUTH_TOKEN_GENERATE = "auth.token_generate"
AUTH_TOKEN_REMOVE = "auth.token_remove"

# Console
CONSOLE_CREATE = "console.create"
CONSOLE_LIST = "console.list"
CONSOLE_DESTROY = "console.destroy"
CONSOLE_READ = "console.read"
CONSOLE_WRITE = "console.write"
CONSOLE_TABS = "console.tabs"
CONSOLE_SESSION_KILL = "console.session_kill"
CONSOLE_SESSION_DETACH = "console.session_detach"

# Core
CORE_VERSION = "core.version"
CORE_STOP = "core.stop"
CORE_GETG = "core.getg"
CORE_SETG = "core.setg"
CORE_UNSETG = "core.unsetg"
CORE_SAVE = "core.save"
CORE_RELOAD_MODULES = "core.reload_modules"
CORE_ADD_MODULE_PATH = "core.add_module_path"
CORE_MODULE_STATS = "core.module_stats"
CORE_THREAD_LIST = "core.thread_list"
CORE_THREAD_KILL = "core.thread_kill"

# DB
DB_CREATE_CRACKED_CREDENTIAL = "db.create_cracked_credential"
DB_CREATE_CREDENTIAL = "db.create_credential"
DB_INVALIDATE_LOGIN = "db.invalidate_login"
DB_CREDS = "db.creds"
DB_DEL_CREDS = "db.del_creds"
DB_HOSTS = "db.hosts"
DB_SERVICES = "db.services"
DB_VULNS = "db.vulns"
DB_WORKSPACES = "db.workspaces"
DB_CURRENT_WORKSPACE = "db.current_workspace"
DB_GET_WORKSPACE = "db.get_workspace"
DB_SET_WORKSPACE = "db.set_workspace"
DB_DEL_WORKSPACE = "db.del_workspace"
DB_ADD_WORKSPACE = "db.add_workspace"
DB_GET_HOST = "db.get_host"
DB_ANALYZE_HOST = "db.analyze_host"
DB_REPORT_HOST = "db.report_host"
DB_REPORT_SERVICE = "db.report_service"
DB_GET_SERVICE = "db.get_service"
DB_GET_NOTE = "db.get_note"
DB_GET_CLIENT = "db.get_client"
DB_REPORT_CLIENT = "db.report_client"
DB_REPORT_NOTE = "db.report_note"
DB_NOTES = "db.notes"
DB_GET_REF = "db.get_ref"
DB_DEL_VULN = "db.del_vuln"
DB_DEL_NOTE = "db.del_note"
DB_DEL_SERVICE = "db.del_service"
DB_DEL_HOST = "db.del_host"
DB_REPORT_VULN = "db.report_vuln"
DB_EVENTS = "db.events"
DB_REPORT_EVENT = "db.report_event"
DB_REPORT_LOOT = "db.report_loot"
DB_LOOTS = "db.loots"
DB_IMPORT_DATA = "db.import_data"
DB_GET_VULN = "db.get_vuln"
DB_CLIENTS = "db.clients"
DB_DEL_CLIENT = "db.del_client"
DB_DRIVER = "db.driver"
DB_CONNECT = "db.connect"
DB_STATUS = "db.status"
DB_DISCONNECT = "db.disconnect"

# Health
HEALTH_CHECK = "health.check"

# Jobs
JOB_LIST = "job.list"
JOB_STOP = "job.stop"
JOB_INFO = "job.info"

# Modules
MODULE_EXPLOITS = "module.exploits"
MODULE_EVASION = "module.evasion"
MODULE_AUXILIARY = "module.auxiliary"
MODULE_PAYLOADS = "module.payloads"
MODULE_ENCODERS = "module.encoders"
MODULE_NOPS = "module.nops"
MODULE_POST = "module.post"
MODULE_INFO_HTML = "module.info_html"
MODULE_INFO = "module.info"
MODULE_SEARCH = "module.search"  # TODO: does this work?
MODULE_COMPATIBLE_PAYLOADS = "module.compatible_payloads"
MODULE_COMPATIBLE_EVASION_PAYLOADS = "module.compatible_evasion_payloads"
MODULE_COMPATIBLE_SESSIONS = "module.compatible_sessions"
MODULE_TARGET_COMPATIBLE_PAYLOADS = "module.target_compatible_payloads"
MODULE_TARGET_COMPATIBLE_EVASION_PAYLOADS = "module.target_compatible_evasion_payloads"
MODULE_RUNNING_STATS = "module.running_stats"
MODULE_OPTIONS = "module.options"
MODULE_EXECUTE = "module.execute"
MODULE_CHECK = "module.check"
MODULE_RESULTS = "module.results"
MODULE_EXECUTABLE_FORMATS = "module.executable_formats"
MODULE_TRANSFORM_FORMATS = "module.transform_formats"
MODULE_ENCRYPTION_FORMATS = "module.encryption_formats"
MODULE_PLATFORMS = "module.platforms"
MODULE_ARCHITECTURES = "module.architectures"
MODULE_ENCODE_FORMATS = "module.encode_formats"
MODULE_ENCODE = "module.encode"


# Plugins
PLUGIN_LOAD = "plugin.load"
PLUGIN_UNLOAD = "plugin.unload"
PLUGIN_LOADED = "plugin.loaded"

# Sessions
SESSION_LIST = "session.list"
SESSION_STOP = "session.stop"
SESSION_SHELL_READ = "session.shell_read"
SESSION_SHELL_WRITE = "session.shell_write"
SESSION_SHELL_UPGRADE = "session.shell_upgrade"
SESSION_METERPRETER_READ = "session.meterpreter_read"
SESSION_METERPRETER_WRITE = "session.meterpreter_write"
SESSION_METERPRETER_SESSION_DETACH = "session.meterpreter_session_detach"
SESSION_METERPRETER_SESSION_KILL = "session.meterpreter_session_kill"
SESSION_METERPRETER_TABS = "session.meterpreter_tabs"
SESSION_METERPRETER_RUN_SINGLE = "session.meterpreter_run_single"
SESSION_METERPRETER_SCRIPT = "session.meterpreter_script"
SESSION_METERPRETER_TRANSPORT_CHANGE = "session.meterpreter_transport_change"
SESSION_METERPRETER_DIRECTORY_SEPARATOR = "session.meterpreter_directory_separator"
SESSION_COMPATIBLE_MODULES = "session.compatible_modules"
SESSION_RING_READ = "session.ring_read"
SESSION_RING_PUT = "session.ring_put"
SESSION_RING_LAST = "session.ring_last"
SESSION_RING_CLEAR = "session.ring_clear"
